version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/configure_server
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: scripts/prepare_bind_mount
  #     timeout: 300
  #     runas: root
  # ApplicationStart:
  #   - location: scripts/start_application
  #     timeout: 300
  #     runas: root
  # ApplicationStop:
  #   - location: scripts/stop_application
  #     timeout: 300
  #     runas: root
