version: 0.0
os: linux
files:
  - source: index.html
    destination: /usr/share/nginx/html/
  # - source: /html
  #   destination: /var/www/magento/
  # - source: /php/php.ini
  #   destination: /etc/
  # - source: /php/www.conf
  #   destination: /etc/php-fpm.d/
  # - source: /nginx/nginx.conf
  #   destination: /etc/nginx/
  # - source: /nginx/magento.conf
  #   destination: /etc/nginx/magento/
  # - source: /nginx/app.conf
  #   destination: /etc/nginx/conf.d/
hooks:
  BeforeInstall:
    - location: scripts/configure_server
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: scripts/prepare_bind_mount
  #     timeout: 300
  #     runas: root
  # ApplicationStart:
  #   - location: scripts/start_application
  #     timeout: 300
  #     runas: root
  # ApplicationStop:
  #   - location: scripts/stop_application
  #     timeout: 300
  #     runas: root
