#!/bin/bash

#####
# Prepare for overwrite of php-fpm and nginx files
#####
# if [ -e "/etc/php-fpm.d/www.conf" ]
#   then
#     mv -f /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.conf.bk
# fi
# if [ -e "/etc/php.ini" ]
#   then
#     mv -f /etc/php.ini /etc/php.ini.bk
# fi
# if [ -e "/etc/nginx/nginx.conf" ]
#   then
#     mv -f /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bk
# fi
# if [ -e "/etc/nginx/conf.d/app.conf" ]
#   then
#     mv -f /etc/nginx/conf.d/app.conf /etc/nginx/conf.d/app.conf.bk
# fi
# if [ -e "/etc/nginx/magento/magento.conf" ]
#   then
#     mv -f /etc/nginx/magento/magento.conf /etc/nginx/magento/magento.conf.bk
# fi

#####
# Create Magento web directory
#####
# if [ ! -d "/etc/nginx/magento" ]
#   then
#     mkdir -p /etc/nginx/magento
#     chown -R nginx:nginx /etc/nginx/magento
#   else
#   	echo "Nginx conf directory /etc/nginx/magento already installed..";
# fi


#####
# Create Magento web directory
#####
if [ -d "/var/www/magento" ]
  then
    tar -czvf magento_$(date +%Y-%m-%d).tar.gz /var/www/magento
    umount /var/www/magento/pub/media
    rm -rf /var/www/magento
  else
  	echo "backup the web dir";
fi

#####
# Create Magento web directory
#####
if [ ! -d "/var/www/magento" ]
  then
    mkdir -p /var/www/magento
    chown -R nginx:nginx /var/www/magento
  else
  	echo "Web directory /var/www/magento already installed..";
fi

#####
# Install composer
#####
if [ ! -f "/usr/local/bin/composer" ];then
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    php -r "unlink('composer-setup.php');"
else
    /usr/local/bin/composer self-update --stable --no-ansi --no-interaction
fi

#####
# Create a COMPOSER_HOME directory for the application
#####
if [ ! -d "/var/cache/composer" ];then
    mkdir -p /var/cache/composer
    chown www-data.www-data /var/cache/composer
fi
